Update the Dockerfile from using apt-get update and yum update to mee…
swiftlang/swift-docker pull request #194
Opened 2020-08-10 19:55 UTC by shahmishal

…t guidelines by hub.docker.com

https://github.com/docker-library/official-images/pull/8509#issuecomment-670627074

> I'm not sure how we missed it previously, but yum -y update shouldn't be used in Dockerfiles -- we recommend instead asking the base image maintainers to update their images if there are packages in the base image that need to be updated (both because often the packages from the base image will fail to update, but more importantly because it severely bloats the size of the resulting images by including many of the same files twice).

>(This is discussed in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get, https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves, and somewhat in https://github.com/docker-library/official-images#library-definition-files.)

2020-08-10 19:57 UTC, shahmishal commented
@swift-ci test

2020-08-10 20:04 UTC, drexin requested changes
The `apt-get update` is required here, because it updates the package lists. The linked article talks about `apt-get upgrade`, which would upgrade the installed packages (which is what `yum update` also does). So removing `yum update` is correct, removing `apt-get update` is not.

2020-08-10 20:06 UTC, shahmishal commented
@drexin Thanks I will revert the apt-get update

2020-08-10 21:29 UTC, shahmishal commented
@swift-ci test

2020-08-10 21:31 UTC, drexin approved these changes
Thanks you!

2020-08-10 21:31 UTC, tomerd commented
should we do this in the other (nightly, 5.3, etc) docker files too?

2020-08-10 21:40 UTC, tomerd commented
cool! what is https://github.com/apple/swift-docker/tree/master/nightly-5.3 used for? seems like it only has ubuntu?

2020-08-10 22:20 UTC, shahmishal commented
@swift-ci test

2020-08-11 00:45 UTC, shahmishal commented
@swift-ci test

2020-08-11 01:03 UTC, shahmishal commented
@swift-ci test

2020-08-11 01:03 UTC, shahmishal commented
@swift-ci test

2020-08-11 01:03 UTC, shahmishal commented
@swift-ci test

2020-08-11 09:22 UTC, shahmishal commented
@swift-ci test

2020-08-11 17:03 UTC, merged